# Generated by Django 6.1.1 on 2026-09-23 18:15

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.directory.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("description", models.TextField(max_length=3000)),
                ("author", models.CharField(blank=True, max_length=120)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("apps", "Apps & websites"),
                            ("games", "Games"),
                            ("tools", "Developer tools"),
                            ("libraries", "Libraries"),
                            ("research", "Research & experiments"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "website_url",
                    models.URLField(
                        blank=True,
                        max_length=1000,
                        validators=[apps.directory.models.validate_public_url],
                    ),
                ),
                (
                    "repository_url",
                    models.URLField(
                        blank=True,
                        max_length=1000,
                        validators=[apps.directory.models.validate_public_url],
                    ),
                ),
                (
                    "canonical_url",
                    models.URLField(
                        max_length=1000,
                        unique=True,
                        validators=[apps.directory.models.validate_public_url],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("featured", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-featured", "-published_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SubmissionLimit",
            fields=[
                (
                    "key",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("count", models.PositiveIntegerField(default=0)),
                ("expires_at", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="AdminAPIKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "digest",
                    models.CharField(editable=False, max_length=64, unique=True),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("description", models.TextField(max_length=3000)),
                ("author", models.CharField(blank=True, max_length=120)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("apps", "Apps & websites"),
                            ("games", "Games"),
                            ("tools", "Developer tools"),
                            ("libraries", "Libraries"),
                            ("research", "Research & experiments"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "source_url",
                    models.URLField(
                        max_length=1000,
                        validators=[apps.directory.models.validate_public_url],
                    ),
                ),
                (
                    "website_url",
                    models.URLField(
                        blank=True,
                        max_length=1000,
                        validators=[apps.directory.models.validate_public_url],
                    ),
                ),
                (
                    "repository_url",
                    models.URLField(
                        blank=True,
                        max_length=1000,
                        validators=[apps.directory.models.validate_public_url],
                    ),
                ),
                (
                    "contact",
                    models.CharField(
                        blank=True,
                        help_text="Private. Never displayed publicly.",
                        max_length=250,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("review_notes", models.TextField(blank=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="directory.project",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SourceLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        max_length=1000,
                        validators=[apps.directory.models.validate_public_url],
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("github", "GitHub"),
                            ("x", "X"),
                            ("reddit", "Reddit"),
                            ("website", "Website"),
                            ("video", "Video"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sources",
                        to="directory.project",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("project", "url"), name="unique_project_source"
                    )
                ],
            },
        ),
    ]
