# Generated by Django 6.1.1 on 2026-09-24 06:43

from django.db import migrations, models
from django.utils.text import slugify
import uuid


def populate_slugs(apps, schema_editor):
    Project = apps.get_model("directory", "Project")
    db = schema_editor.connection.alias
    used = set()
    for project in Project.objects.using(db).order_by("created_at", "pk").iterator():
        base = slugify(project.title)[:120] or "project"
        try:
            uuid.UUID(base)
        except ValueError:
            pass
        else:
            base = f"build-{base}"
        slug = base
        suffix = 0
        while slug in used:
            suffix += 1
            slug = f"{base}-{project.pk.hex}-{suffix}"
        used.add(slug)
        Project.objects.using(db).filter(pk=project.pk).update(slug=slug)


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='github_stars',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='github_stars_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='x_likes',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.RunPython(populate_slugs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="project", name="slug",
            field=models.SlugField(blank=True, max_length=160, unique=True),
        ),
    ]
