# Generated by Django 6.1.1 on 2026-09-24 08:44

import apps.directory.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0002_project_github_stars_project_github_stars_checked_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsorship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('business_name', models.CharField(max_length=80)),
                ('website_url', models.URLField(max_length=1000, validators=[apps.directory.models.validate_public_url])),
                ('tagline', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('pending', 'Awaiting payment'), ('paid', 'Paid'), ('revoked', 'Refunded or disputed')], default='pending', max_length=16)),
                ('hidden', models.BooleanField(default=False, help_text='Hide an inappropriate placement.')),
                ('stripe_price_id', models.CharField(max_length=100)),
                ('checkout_session_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('checkout_url', models.URLField(blank=True, max_length=2048)),
                ('payment_intent_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['starts_at', 'created_at'],
            },
        ),
    ]
