# Generated by Django 6.1.1 on 2026-09-24 09:08

import apps.directory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0003_sponsorship'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='thumbnail_url',
            field=models.URLField(blank=True, help_text='Optional direct HTTPS link to a screenshot or example image, not a webpage.', max_length=2000, validators=[apps.directory.models.validate_thumbnail_url]),
        ),
        migrations.AddField(
            model_name='submission',
            name='thumbnail_url',
            field=models.URLField(blank=True, help_text='Optional direct HTTPS link to a screenshot or example image, not a webpage.', max_length=2000, validators=[apps.directory.models.validate_thumbnail_url]),
        ),
    ]
