# Generated by Django 6.1.1 on 2026-09-24 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0004_project_thumbnail_url_submission_thumbnail_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='thumbnail_attempted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='thumbnail_error',
            field=models.CharField(blank=True, editable=False, max_length=40),
        ),
        migrations.AddField(
            model_name='project',
            name='thumbnail_imported_source',
            field=models.URLField(blank=True, editable=False, max_length=2000),
        ),
        migrations.AddField(
            model_name='project',
            name='thumbnail_key',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
    ]
